### ISSUE TITLE
Missing 3 input files: libnvinfer_plugin.so, libcudnn.so and libnvinfer.so

### ISSUE THREAD

**Issue by fschvart** [NVIDIA/Torch-TensorRT#1019]
## ❓ Question
I've been looking at all the great progress done previously when it comes to using Torch-TensorRT on Windows. 
I made progress to the point that it seems like only 1 thing is missing. I'm missing the 3 .so mentioned above. 
How are they supposed to be built? Am I missing something? Is there any fix that I missed? 

## What you have already tried

I followed the guides from from #856 

## Environment

Windows 10, trying to build for Visual Studio usage

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.11.0
 - CPU Architecture:  i9
 - OS (e.g., Linux):  Windows 10
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): libtorch
 - Build command you used (if compiling from source):  bazel
 - Are you using local sources or building from archives: building from archive
 - Python version: 3.9
 - CUDA version: 11.5
 - GPU models and configuration:  RTX3090

**Comment by jonahclarsen** [comment]
.a and .so files are linux library files, you need to modify the cpp/lib/BUILD file to include the Windows equivalents (i.e. .lib and .dll). See #690.

**Comment by fschvart** [comment]
I solved the problem. One thig that #856 is taking for granted is that everyone installed Torch-TensorRT locally, since I used the file:// version, I needed to change not the local/build, but the archive/build.
